apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Modo de acesso para um nó (ReadWriteMany para vários nós)
  resources:
    requests:
      storage: 10Gi   # Tamanho do armazenamento solicitado
